// Generated by Wrangler by running `wrangler types`

interface Env {
	WORKOS_CLIENT_ID: "client_01M07XGHQJENJASNY4P2CM2E11";
	ALLOWED_ORIGIN: "*";
	SYNC_STATE: DurableObjectNamespace<import("./src/index").SyncState>;
}
